### ISSUE TITLE
RuntimeError: ``local_state_dict`` can only be used when parameters are flatten and sharded.

### ISSUE THREAD

**Issue by dqgdqg** [facebookresearch/dinov2#273]
I tried to pretrain DINOv2 model on ImageNet1K using the fast setting given in readme. Initially, the loss decreased gradually and everything was normal. However, after several hours, the RuntimeError was encountered as the following:

...
I20231018 19:10:40 3596434 dinov2 helpers.py:102] Training  [  3700/125000]  eta: 1 day, 11:01:46  lr: 0.0002 (0.0001)  wd: 0.0408 (0.0403)  mom: 0.9920 (0.9920)  last_layer_lr: 0.0002 (0.0001)  current_batch_size: 32.0000 (32.0000)  total_loss: 12.8138 (13.1787)  dino_local_crops_loss: 9.3369 (9.5248)  dino_global_crops_loss: 1.1623 (1.1884)  koleo_loss: -0.0216 (0.0094)  ibot_loss: 2.3386 (2.4561)  time: 1.031760  data: 0.000136  max mem: 20017
I20231018 19:10:51 3596434 dinov2 helpers.py:102] Training  [  3710/125000]  eta: 1 day, 11:01:34  lr: 0.0002 (0.0001)  wd: 0.0408 (0.0403)  mom: 0.9920 (0.9920)  last_layer_lr: 0.0002 (0.0001)  current_batch_size: 32.0000 (32.0000)  total_loss: 12.8138 (13.1777)  dino_local_crops_loss: 9.3525 (9.5243)  dino_global_crops_loss: 1.1665 (1.1883)  koleo_loss: -0.0216 (0.0093)  ibot_loss: 2.3422 (2.4559)  time: 1.032206  data: 0.000132  max mem: 20017
I20231018 19:11:01 3596434 dinov2 helpers.py:102] Training  [  3720/125000]  eta: 1 day, 11:01:20  lr: 0.0002 (0.0001)  wd: 0.0408 (0.0403)  mom: 0.9920 (0.9920)  last_layer_lr: 0.0002 (0.0001)  current_batch_size: 32.0000 (32.0000)  total_loss: 12.8332 (13.1768)  dino_local_crops_loss: 9.3451 (9.5237)  dino_global_crops_loss: 1.1597 (1.1882)  koleo_loss: -0.0216 (0.0092)  ibot_loss: 2.3851 (2.4557)  time: 1.032348  data: 0.000133  max mem: 20017
I20231018 19:11:11 3596434 dinov2 helpers.py:102] Training  [  3730/125000]  eta: 1 day, 11:01:09  lr: 0.0002 (0.0001)  wd: 0.0408 (0.0403)  mom: 0.9920 (0.9920)  last_layer_lr: 0.0002 (0.0001)  current_batch_size: 32.0000 (32.0000)  total_loss: 12.8332 (13.1757)  dino_local_crops_loss: 9.3334 (9.5232)  dino_global_crops_loss: 1.1597 (1.1881)  koleo_loss: -0.0217 (0.0091)  ibot_loss: 2.3650 (2.4553)  time: 1.032516  data: 0.000132  max mem: 20017
I20231018 19:11:22 3596434 dinov2 helpers.py:102] Training  [  3740/125000]  eta: 1 day, 11:00:55  lr: 0.0002 (0.0001)  wd: 0.0408 (0.0403)  mom: 0.9920 (0.9920)  last_layer_lr: 0.0002 (0.0001)  current_batch_size: 32.0000 (32.0000)  total_loss: 12.8134 (13.1747)  dino_local_crops_loss: 9.3318 (9.5226)  dino_global_crops_loss: 1.1600 (1.1880)  koleo_loss: -0.0218 (0.0090)  ibot_loss: 2.3561 (2.4550)  time: 1.033008  data: 0.000132  max mem: 20017
Traceback (most recent call last):
  File "/home/qgding/research/dasdino/dinov2/dinov2/train/train.py", line 320, in <module>
    main(args)
  File "/home/qgding/research/dasdino/dinov2/dinov2/train/train.py", line 315, in main
    do_train(cfg, model, resume=not args.no_resume)
  File "/home/qgding/research/dasdino/dinov2/dinov2/train/train.py", line 292, in do_train
    periodic_checkpointer.step(iteration)
  File "/home/qgding/.conda/envs/dino/lib/python3.9/site-packages/fvcore/common/checkpoint.py", line 428, in step
    self.checkpointer.save(
  File "/home/qgding/research/dasdino/dinov2/dinov2/fsdp/__init__.py", line 99, in save
    data["model"] = self.model.state_dict()
  File "/home/qgding/.conda/envs/dino/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/home/qgding/.conda/envs/dino/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/home/qgding/.conda/envs/dino/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1815, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "/home/qgding/.conda/envs/dino/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1722, in _save_to_state_dict
    hook(self, prefix, keep_vars)
  File "/home/qgding/.conda/envs/dino/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/qgding/.conda/envs/dino/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 669, in _pre_state_dict_hook
    _pre_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "/home/qgding/.conda/envs/dino/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 359, in _local_pre_state_dict_hook
    raise RuntimeError(
**RuntimeError: ``local_state_dict`` can only be used when parameters are flatten and sharded.**

Anyone has the same issue? It seems like the error is related to FSDP.

**Comment by dqgdqg** [comment]
Solved.

              You may notice that if you are using a single node, Dino will automatically revert to using normal data parallelism instead of fully sharded. In this case, you may still get the local_state_dict error. You can also address this by using a full state dict instead of local state in dinov2/fsdp/__init__.py, changing to `with FSDP.state_dict_type(self.model, StateDictType.FULL_STATE_DICT):` instead of `with FSDP.state_dict_type(self.model, StateDictType.LOCAL_STATE_DICT):`

_Originally posted by @sfilios in https://github.com/facebookresearch/dinov2/issues/134#issuecomment-1623629263_
