### ISSUE TITLE
Unable to load dinov2 with registers on local machine 

### ISSUE THREAD

**Issue by smeenap** [facebookresearch/dinov2#309]
>>> dinov2_vits14_reg = torch.hub.load('facebookresearch/dinov2', 'dinov2_vits14_reg')
Using cache found in /home/vplab/.cache/torch/hub/facebookresearch_dinov2_main
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home//anaconda3/envs/dinov2/lib/python3.9/site-packages/torch/hub.py", line 566, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home//anaconda3/envs/dinov2/lib/python3.9/site-packages/torch/hub.py", line 594, in _load_local
    entry = _load_entry_from_hubconf(hub_module, model)
  File "/home//anaconda3/envs/dinov2/lib/python3.9/site-packages/torch/hub.py", line 348, in _load_entry_from_hubconf
    raise RuntimeError(f'Cannot find callable {model} in hubconf')
RuntimeError: Cannot find callable dinov2_vits14_reg in hubconf

**Comment by qasfb** [comment]
I think it could be a cache issue, can you try with torch.hub.load(..., force_reload=True) ?

Same as this: https://github.com/facebookresearch/dinov2/issues/296

**Comment by c1scott** [comment]
having the same issue

`import torch
from torchvision import models, transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image
from sklearn.svm import SVC
from sklearn.metrics import classification_report
import numpy as np
import tqdm
import json

# Define transformations for DINO-v2
transform_image = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize(244),
    transforms.CenterCrop(224),
    transforms.Normalize([0.5], [0.5])
])

# Load the DINOv2 model
dinov2_vits14 = torch.hub.load("facebookresearch/dinov2", "dino_vits14", force_reload=True)
device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
dinov2_vits14.to(device)

def load_image(img_path: str) -> torch.Tensor:
    """
    Load an image and return a tensor that can be used as an input to DINOv2.
    """
    img = Image.open(img_path)
    transformed_img = transform_image(img)[:3].unsqueeze(0)
    return transformed_img

def compute_embeddings(dataset: Dataset) -> dict:
    """
    Compute embeddings for each image in the dataset.
    """
    all_embeddings = {}
    labels = []

    with torch.no_grad():
        for img_path, label in tqdm.tqdm(dataset):
            embeddings = dinov2_vits14(load_image(img_path).to(device))
            all_embeddings[img_path] = np.array(embeddings[0].cpu().numpy()).reshape(1, -1).tolist()[0]
            labels.append(label)

    return all_embeddings, labels

# Create datasets and data loaders
train_dataset = ImageDataset(train_df, transform=transform_image)
validation_dataset = ImageDataset(validation_df, transform=transform_image)

# Compute embeddings
train_embeddings, train_labels = compute_embeddings(train_dataset)
validation_embeddings, validation_labels = compute_embeddings(validation_dataset)

# Convert embeddings to numpy arrays for training
train_features = np.array(list(train_embeddings.values()))
validation_features = np.array(list(validation_embeddings.values()))

# Train a classifier (e.g., SVM)
classifier = SVC(gamma='scale')
classifier.fit(train_features, train_labels)

# Evaluate the classifier
predicted_labels = classifier.predict(validation_features)
print(classification_report(validation_labels, predicted_labels))
`

And the output error

`Downloading: "https://github.com/facebookresearch/dinov2/zipball/main" to [C:\Users\q42/.cache\torch\hub\main.zip](file:///C:/Users/q42/.cache/torch/hub/main.zip)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[d:\report\dinov2](file:///D:/report/dinov2) classify ff images.ipynb Cell 3 line 2
     [12](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=11) transform_image = transforms.Compose([
     [13](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=12)     transforms.ToTensor(),
     [14](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=13)     transforms.Resize(244),
     [15](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=14)     transforms.CenterCrop(224),
     [16](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=15)     transforms.Normalize([0.5], [0.5])
     [17](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=16) ])
     [19](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=18) # Load the DINOv2 model
---> [20](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=19) dinov2_vits14 = torch.hub.load("facebookresearch/dinov2", "dino_vits14", force_reload=True)
     [21](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=20) device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
     [22](vscode-notebook-cell:/d%3A/report/dinov2%20classify%20ff%20images.ipynb#W4sZmlsZQ%3D%3D?line=21) dinov2_vits14.to(device)

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\hub.py:558](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:558), in load(repo_or_dir, model, source, trust_repo, force_reload, verbose, skip_validation, *args, **kwargs)
    [554](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:554) if source == 'github':
    [555](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:555)     repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
    [556](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:556)                                        verbose=verbose, skip_validation=skip_validation)
--> [558](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:558) model = _load_local(repo_or_dir, model, *args, **kwargs)
    [559](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:559) return model

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\hub.py:586](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:586), in _load_local(hubconf_dir, model, *args, **kwargs)
    [583](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:583)     hubconf_path = os.path.join(hubconf_dir, MODULE_HUBCONF)
    [584](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:584)     hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
--> [586](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:586)     entry = _load_entry_from_hubconf(hub_module, model)
    [587](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:587)     model = entry(*args, **kwargs)
    [589](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:589) return model

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\hub.py:340](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:340), in _load_entry_from_hubconf(m, model)
    [337](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:337) func = _load_attr_from_module(m, model)
    [339](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:339) if func is None or not callable(func):
--> [340](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:340)     raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
    [342](https://file+.vscode-resource.vscode-cdn.net/d%3A/report/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/torch/hub.py:342) return func

RuntimeError: Cannot find callable dino_vits14 in hubconf`
