### ISSUE TITLE
AttributeError: 'DinoVisionTransformer' object has no attribute '_streams'

### ISSUE THREAD

**Issue by davidanglada** [facebookresearch/dinov2#310]
I'm trying to reproduce the training of the DinoV2 on ImageNet 1K. This is the submited job:

```
#!/bin/bash

#Parameters
#SBATCH --cpus-per-task=1
#SBATCH --error=/mnt/work/users/david.anglada/PhD/dinov2_ckpts/%j_0_log.err
#SBATCH --gpus-per-node=1
#SBATCH --job-name=dinov2:train
#SBATCH --mem=0GB
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --open-mode=append
#SBATCH --output=/mnt/work/users/david.anglada/PhD/dinov2_ckpts/%j_0_log.out
#SBATCH --partition=gpi.compute
#SBATCH --signal=USR2@120
#SBATCH --time=1440
#SBATCH --wckey=submitit

#command
export SUBMITIT_EXECUTOR=slurm
srun --unbuffered --output /mnt/work/users/david.anglada/PhD/dinov2_ckpts/%j_%t_log.out --error /mnt/work/users/david.anglada/PhD/dinov2_ckpts/%j_%t_log.err /home/usuaris/imatge/david.anglada/venv/phd2/bin/python -u -m submitit.core._submit /mnt/work/users/david.anglada/PhD/dinov2_ckpts
```

But I get the following error:

```
submitit ERROR (2023-11-15 13:22:17,349) - Submitted job triggered an exception
E20231115 13:22:17 220932 submitit submission.py:68] Submitted job triggered an exception
david.anglada@gpie04:/mnt/work/users/david.anglada/PhD/dinov2_ckpts$ cat 636_0_log.err
/home/usuaris/imatge/david.anglada/PhD/mic/dinov2/dinov2/layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/usuaris/imatge/david.anglada/PhD/mic/dinov2/dinov2/layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/usuaris/imatge/david.anglada/PhD/mic/dinov2/dinov2/layers/block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
submitit ERROR (2023-11-15 13:22:17,349) - Submitted job triggered an exception
Traceback (most recent call last):
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 527, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'FullyShardedDataParallel' object has no attribute '_streams'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/submitit/core/submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/submitit/core/submission.py", line 69, in process_job
    raise error
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/home/usuaris/imatge/david.anglada/PhD/mic/dinov2/dinov2/run/train/train.py", line 26, in __call__
    train_main(self.args)
  File "/home/usuaris/imatge/david.anglada/PhD/mic/dinov2/dinov2/train/train.py", line 313, in main
    do_train(cfg, model, resume=not args.no_resume)
  File "/home/usuaris/imatge/david.anglada/PhD/mic/dinov2/dinov2/train/train.py", line 245, in do_train
    loss_dict = model.forward_backward(data, teacher_temp=teacher_temp)
  File "/home/usuaris/imatge/david.anglada/PhD/mic/dinov2/dinov2/train/ssl_meta_arch.py", line 344, in forward_backward
    self.fsdp_synchronize_streams()
  File "/home/usuaris/imatge/david.anglada/PhD/mic/dinov2/dinov2/train/ssl_meta_arch.py", line 353, in fsdp_synchronize_streams
    ) = self.student.backbone._streams = self.teacher.backbone._streams
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 529, in __getattr__
    return getattr(self._fsdp_wrapped_module, name)
  File "/home/usuaris/imatge/david.anglada/venv/phd2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DinoVisionTransformer' object has no attribute '_streams'
srun: error: gpic14: task 0: Exited with exit code 1
```

How can I solve this error? 

Thank you very much!

**Comment by qasfb** [comment]
This is because of pytorch 2.1, we haven't adapted the code on our side yet but you can check that PR https://github.com/facebookresearch/dinov2/pull/281
