### ISSUE TITLE
Requirements are uncompatible

### ISSUE THREAD

**Issue by Antoine-Audras** [facebookresearch/dinov2#428]
I am trying to run the `semantic_segmentation.ipynb` notebook which requires the MMCV library.

I tried installing MMCV and mmsegmentation as specified by the `requirements-extra.txt`, which specifies the `mmcv-full==1.5.0`, but I think this requirement is incompatible with `torch==2.0.0` from `requirements.txt`.

This results in a build error :
```
      ...

      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-b3rmsfn9/mmcv-full_c769ad7fee444417994e0233614b59ac/setup.py", line 393, in <module>
          setup(
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/antoineaudras/.pyenv/versions/3.10.14/envs/dinov2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects
```

If you inspect the link `mim` or `pip` tried to get the precompiled mmcv from : https://download.openmmlab.com/mmcv/dist/cu117/torch2.0.0/index.html

You can see that there is no binary pre-built for these specific requirements.

Moreover, by looking at the [release page](https://github.com/open-mmlab/mmcv/releases?page=1) for MMCV, we can see that pre-built binaries compatible with Torch v2.0.0 start with MMCV v1.7.2

**Comment by Antoine-Audras** [comment]
I would have liked to run the experiment with the latest MMCV version, but unfortunately the 2.0.0 release introduced breaking changes making it incompatible with the code from the notebook.

**Comment by ayushnangia** [comment]
yep i am unable to even build the env

**Comment by Antoine-Audras** [comment]
I have managed to get a frankensteinish setup going, I installed dinov2 requirements without `xformers` and `torch==1.11` (to satisfy the `requirements-extras.txt` because Torch v11.1 is the last version compatible with MMCV v1.5.0) compiled with CUDA 11.5. Then I installed `mmcv-full` v1.5.0 and `mmsegmentation==0.27.0`. 

This can run the code but I get CUDA out of memory errors. My best guess is that xformers is required to reduce the model's size and without that dependency the models just don't fit into my VRAM. Or this could be a completly unrelated error, who knows 
¯ \ _ (ツ) _ / ¯ .

Anyway the choice of using MMCV is more than questionable, this library is a complete dumpster fire.

**Comment by ayushnangia** [comment]
can you share a docker file for this ?

**Comment by ayushnangia** [comment]
@Antoine-Audras  https://github.com/facebookresearch/dinov2/pull/370
try this out

**Comment by mfoglio** [comment]
Hey @Antoine-Audras and @ayushnangia , I am having issues setting up a virtual environment to run the segmentation.
Why are you using CUDA 11.6? It looks like CUDA 11.7 it's the suggest one according to the requirements.txt

**Comment by Antoine-Audras** [comment]
> Why are you using CUDA 11.6? It looks like CUDA 11.7

It was the latest version that was compatible with the version of MMCV and Torch I was trying to run (I tried to deduce that from the compatibility matrix, but turns out the info is only partially right). 

But now I have managed to set up an environment with the required specs. All you have to do is : install `requirements.txt`, install `openmim` and with that install the required version of MMCV and `mmsegmentation`. If you try to run the experiment at this point you will have a message about a missing `_ext` file. In order to fix that, you have to build MMCV from source with the right version of Torch and CUDA (I used 2.0.0 and 11.7 respectively, as specified by the requirements) and then you should find the `_ext` file in the build artefacts (something like `mmcv/build/lib.linux-x86_64-3.10/mmcv/_ext.cpython-310-x86_64-linux-gnu.so`) and copy it in your mmcv folder in your python site-package (where your packages are installed).

Anyway, as I have stated before, MMCV is a garbage library that should never be used, all it does is obfuscate code and make it harder to reproduce the results from the paper.

Hopefully that will help.

**Comment by danbgoldman** [comment]
I wasn't able to use openmim due to firewall restrictions, but I was able to get the segmentation notebook running with only pip install, using CUDA 11.7, torch==2.0.0, torchvision==0.15.1, mmcv-full==1.7.1, and mmsegmentation==0.30.0.
